# Generated by Django 4.0.5 on 2022-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='filtered_accounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='final_accounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='is_running',
            field=models.BooleanField(default=False, help_text='whether the user open or not'),
        ),
        migrations.AddField(
            model_name='license',
            name='total_accounts',
            field=models.IntegerField(default=0),
        ),
    ]
