# Generated by Django 4.0.5 on 2022-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0002_license_filtered_accounts_license_final_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='checker_accounts',
            field=models.IntegerField(default=0),
        ),
    ]
